### ISSUE TITLE
HTML and NaN values

### ISSUE THREAD

**Issue by celevra** [wpovernight/wpo-ips-xrechnung#1]
Hi,

thank you for providing the xrechnung addon!
in a fast test i see a few errors like HTML and NaN in some fields.
I can provide screenshots, but if you provide an e-mail i can send a pdf and a xml file to see the problems.

![image](https://github.com/user-attachments/assets/cfc918b1-b0a9-485f-89a8-5af5496bc885)

![image](https://github.com/user-attachments/assets/d4c07c1c-f85d-40d9-8771-95a50e489b29)

![image](https://github.com/user-attachments/assets/5bffb6ae-4afe-41bf-9389-16765f8d5743)

regards

**Comment by alexmigf** [comment]
Hi @celevra 

Thank you for bringing this to our attention. You could send to our [email address](mailto:support@wpovernight.com).

**Comment by celevra** [comment]
mail is sent
